### ISSUE TITLE
REQUIREMENT Nr. 12: Solutions

### ISSUE THREAD

**Issue by Nicola3341246** [titepasile/HauptprojektIDPA#10]
# Description

For every Job the maker should be able to make Solutions.

- [x]  Requirement is mandatory

## Subtasks

- [ ] Create unittests
- [x] Implement Soltutions in the Backend
- [x] Implement Solutions for the front end
