### ISSUE TITLE
REQUIREMENT Nr. 13: Assigning jobs to a class

### ISSUE THREAD

**Issue by Nicola3341246** [titepasile/HauptprojektIDPA#12]
# Description

Every job made by the named teacher should be able to be distributed to a class. He should have a overview of the jobs he has distributed. The students should get access to the jobs.

- [x]  Requirement is mandatory

## Subtasks

- [ ] Create unittests
- [ ] Implement backend
- [ ] Create overview for teacher
- [ ] Implement access to students
