### ISSUE TITLE
REQUIREMENT Nr. 8-11: Jobs

### ISSUE THREAD

**Issue by Nicola3341246** [titepasile/HauptprojektIDPA#7]
# Description

A user can make new job for a class / group. It should have a description with max. 250 Characters and a max. of 50 booking rates.

- [x]  Requirement is mandatory

## Subtasks

- [ ] Create unittests
- [x] Implement backend requirements
- [x] Implementing making a new job
- [x] Edit job
- [x] Delete job

**Comment by Nicola3341246** [comment]
As far as I know has been implemented
