### ISSUE TITLE
REQUIREMENT Nr. 7: Get in a class via Code

### ISSUE THREAD

**Issue by CevapiMitKajmak** [titepasile/HauptprojektIDPA#8]
# Description

There is a need for getting in a class group as a student. They should get in via Code (the group's ID).

- [x]  Requirement is mandatory

## Subtasks

- [ ] Create unittests
- [ ] Implement requirement with TDD
- [ ] Implement database for class-ID
- [ ] Implement function to join a class
